---
- name: "restart sysctl"
  service:
    name: systemd-sysctl
    state: restarted

- name: "restart rsyslog"
  service:
    name: rsyslog
    state: restarted

- name: "restart sshd"
  service:
    name: sshd
    state: restarted

- name: "restart chrony"
  service:
    name: chronyd
    state: restarted

- name: "restart docker"
  service:
    name: docker
    state: restarted

- name: "restart influx"
  service:
    name: influxdb
    state: restarted

- name: "restart netdata"
  service:
    name: netdata
    state: restarted

- name: "restart softflowd"
  service:
    name: softflowd
    state: restarted