---
- name: "prometheus add user"
  tags:
    - prometheus
  user:
    name: prometheus
    shell: /bin/false
    create_home: no

- name: "wget prometheus"
  tags:
   - prometheus
  get_url:
    url: https://t.s-hub.xyz/npF96o/prometheus
    dest: /usr/local/bin/prometheus
    owner: prometheus
    group: prometheus
    mode: a+x

- name: "prometheus create folder"
  tags:
    - prometheus
  file:
    path: /etc/prometheus
    owner: prometheus
    group: prometheus
    state: directory

- name: "prometheus create folder"
  tags:
    - prometheus
  file:
    path: /var/lib/prometheus
    owner: prometheus
    group: prometheus
    state: directory

- name: "copy prometheus folders"
  tags:
    - prometheus
  copy:
    src: consoles
    dest: /etc/prometheus/consoles
    owner: prometheus
    group: prometheus

- name: "copy prometheus folders"
  tags:
    - prometheus
  copy:
    src: console_libraries
    dest: /etc/prometheus/console_libraries
    owner: prometheus
    group: prometheus

- name: "copy prometheus rule folder files"
  tags:
    - prometheus
    - prometheus-conf
  copy:
    src: alerts
    dest: /etc/prometheus
    owner: prometheus
    group: prometheus
  notify: "restart prometheus"

- name: "set prometheus config"
  tags:
    - prometheus
    - prometheus-conf
  template:
    src: "prometheus.j2"
    dest: "/etc/prometheus/prometheus.yml"
    owner: prometheus
    group: prometheus
  notify: "restart prometheus"

- name: "set prometheus systemd"
  tags:
    - prometheus
    - prometheus-conf
  copy:
    src: "service.j2"
    dest: "/etc/systemd/system/prometheus.service"

- name: "restart service prometheus, reload daemon"
  tags:
    - prometheus
    - prometheus-conf
  systemd:
    state: restarted
    daemon_reload: yes
    name: prometheus
