app_name: mdcup
app_zone: rdc
gunicorn_port: 37180
domain: maildesigncup.ru
domain_nginx: russiandesigncup.ru

database_host: "{{ mysql_master_host }}"
database_user: mdcup
database_password: "{{ rdc_vault_database_password }}"

secret_key: "{{ rdc_vault_secret_key }}"

celery_broker_url: "redis://{{ redis_master_host }}:6379/1"
redis_cache_url: "redis://{{ redis_master_host }}:6379/0"

email_host: mxx.tp.smailru.net
email_port: 25
unsubscribe_token: qVh07oDfV6p8Hc7nDBYS04IDCfegN9qF

ok_client_key: "{{ rdc_vault_ok_client_key }}"
ok_app_key: "{{ rdc_vault_ok_app_key }}"
ok_client_secret: "{{ rdc_vault_ok_client_secret }}"

vk_app_id: "{{ rdc_vault_vk_app_id }}"
vk_api_secret: "{{ rdc_vault_vk_api_secret }}"

twitter_consumer_key: "{{ rdc_vault_twitter_consumer_key }}"
twitter_consumer_secret: "{{ rdc_vault_twitter_consumer_secret }}"
twitter_widget_id: "{{ rdc_vault_twitter_widget_id }}"

facebook_app_id: "{{ rdc_vault_fb_app_id }}"
facebook_api_secret: "{{ rdc_vault_fb_api_secret }}"

cups_api_token: "{{ rdc_vault_cups_api_token }}"